// Generated by CoffeeScript 2.2.4
(function() {
  var _, assert, test, util, xza;

  assert = require('assert');

  _ = require('lodash');

  ({test} = require('ava'));

  xza = require('../');

  util = xza.utility;

  test('util.sizeof', function(t) {
    var obj;
    t.is(util.sizeof(1999), '8 B');
    obj = (function() {
      var results = [];
      for (var j = 0; j <= 10000; j++){ results.push(j); }
      return results;
    }).apply(this).map(function(i) {
      return {
        name: `testName${i}`,
        value: i
      };
    });
    return t.is(util.sizeof(obj), '576 kB');
  });

}).call(this);
