// Generated by CoffeeScript 2.2.4
(function() {
  var _, collection, moment, prettyBytes, sizeof, sma;

  _ = require('lodash');

  sizeof = require('object-sizeof');

  prettyBytes = require('pretty-bytes');

  moment = require('moment');

  sma = require('sma');

  collection = {
    addSma: function(arr, range = 3, key = 0, newkey = 'sma') {
      var vals;
      vals = arr.map(function(item) {
        return item[key];
      });
      sma = sma(vals, range);
      arr.forEach(function(item, i) {
        if (range - 1 <= i) {
          return item[newkey] = Number(sma[i - range + 1]);
        }
      });
      return arr;
    },
    addTotal: function(arr, fromKey = 'value', newKey = 'total') {
      var total;
      total = 0;
      arr.forEach(function(item) {
        total += item[fromKey];
        return item[newKey] = total;
      });
      return arr;
    },
    keys: ['totalPL', 'totalProfit', 'totalloss', 'tradeLength', 'winningPercentage', 'winningCount', 'losingCount', 'maxWinningValue', 'maxLosingValue', 'avarageProfit', 'avarageLoss']
  };

  module.exports = collection;

}).call(this);
