// Generated by CoffeeScript 2.2.4
(function() {
  var _, utility;

  _ = require('lodash');

  utility = require('./utility');

  _.mixin({
    sizeof: utility.sizeof
  });

  _.mixin({
    strToNumber: utility.strToNumber
  });

  module.exports = {
    utility: utility,
    lodash: _
  };

}).call(this);
