// Generated by CoffeeScript 2.2.4
(function() {
  var Big, _, args2, getDiffRate, math;

  _ = require('lodash');

  Big = require('big.js');

  args2 = require('args2');

  getDiffRate = function(base, target, round) {
    var _base, res;
    // (target - base) / abs(base)
    res = new Big(target).minus(base);
    _base = new Big(base).abs();
    return res.div(_base);
  };

  math = {
    diffRate: function(base, target, round) {
      var e;
      try {
        round = round != null ? round : 2;
        return Number(getDiffRate(base, target).times(100).round(round));
      } catch (error) {
        e = error;
        return 0/0;
      }
    },
    progressRate: function(target, progress, round) {
      var _diffRate, e;
      try {
        if (target === 0) {
          // 1 + ((target - base) / abs(base))
          return 0/0;
        }
        round = round != null ? round : 2;
        _diffRate = getDiffRate(target, progress);
        return Number(new Big(1).plus(_diffRate).times(100).round(round));
      } catch (error) {
        e = error;
        return 0/0;
      }
    }
  };

  module.exports = math;

}).call(this);
