// Generated by CoffeeScript 2.2.4
(function() {
  var _, prettyBytes, sizeof;

  _ = require('lodash');

  sizeof = require('object-sizeof');

  prettyBytes = require('pretty-bytes');

  module.exports = {
    sizeof: function(obj) {
      return prettyBytes(sizeof(obj));
    },
    strToNumber: function(str, returnValue = 0/0) {
      var num;
      str = str.replace(/^[△▲Δ](.*)/, '-$1');
      num = Number(str.split(',').join('').trim());
      if (_.isNaN(num)) {
        return returnValue;
      } else {
        return num;
      }
    }
  };

}).call(this);
