// Generated by CoffeeScript 2.2.4
(function() {
  var _, prettyBytes, sizeof;

  _ = require('lodash');

  sizeof = require('object-sizeof');

  prettyBytes = require('pretty-bytes');

  module.exports = {
    sizeof: function(obj) {
      return prettyBytes(sizeof(obj));
    }
  };

}).call(this);
